spring:
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名和下划线命名的自动转换
server:
  servlet:
    context-path: /

---

# 开发环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ganttdb
    username: root
    password: "@MYSQL123jhwsx"
  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081


---

# 测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082

---

# 生产环境
spring:
  config:
    activate:
      on-profile: pro

server:
  port: 8083